;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        counsel-M-x
        disable-mouse--handle
        ignore
        indent-for-tab-command
        kill-region
        mc/vertical-align
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-kill-line
        org-self-insert-command
        phi-search
        yaml-electric-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        yaml-electric-dash-and-dot
        ))
